spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.example.checkers.api, com.example.checkers.controller
  pathsToMatch: /games, /games/*, /games/*/moves, /players, /players/*, /sse/subscribe
  swagger-ui:
    enabled: true
    path: swagger-ui.html

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
