spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.example.checkers.api
  pathsToMatch: /games, /games/*, /games/*/moves, /players, /players/*
  swagger-ui:
    enabled: true
    path: swagger-ui.html

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG